[project]
name = "julia-log"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rlopc4ds", email = "rlopc4ds@gmail.com" }
]
requires-python = ">=3.11,<3.12"
dependencies = []

[project.scripts]
julia-log = "julia_log:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/julia_log"]
