exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "data/",
    "dist",
    "docs/",
    "notebooks/",
    "services/",
    "site-packages",
    "tests/",
    "venv",
]
indent-width = 4
line-length = 120
target-version = "py311"

[lint]
select = ["ALL"]
ignore = [
    "D100", "D101", "D102", "D103", "D104", "D107",
    "D203", "D212",
]

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["INP001", "S101", "ANN001", "ANN202", "ARG002"]

[format]
exclude = ["*.ipynb"]

docstring-code-format = true
docstring-code-line-length = "dynamic" 

indent-style = "space"
line-ending = "auto"
quote-style = "double"

skip-magic-trailing-comma = false
