[project]
name = "julia-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rlopc4ds", email = "rlopc4ds@gmail.com" }
]
requires-python = ">=3.11,<3.12"
dependencies = [
    "langchain-chroma>=0.2.1",
    "langchain-community>=0.3.16",
    "langchain-huggingface>=0.1.2",
    "langchain-openai>=0.3.3",
    "sentence-transformers>=3.4.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
